name = "podium"
compatibility_date = "2024-11-01"
pages_build_output_dir = "."

# Base de datos de reservas. Crea la tuya con:
#   npx wrangler d1 create podium-reservas
# y pega aquí el database_id que te devuelva.
[[d1_databases]]
binding = "DB"
database_name = "podium-reservas"
database_id = "d25baa9b-cb62-4cec-b9b9-93f1d337f2fd"
